dataset:
  repository: https://github.com/Ganapatiknaspl/train-yolo12l-model.git
  local_folder: AerialDataset
  branch: master

training:
  model: yolo12l.pt
  project: YOLO12_Training
  run_name: Aircraft_v12l

status: false  # true = clone/pull dataset, false = skip cloning